test(graphql-transformers-e2e-tests): prevent SES ratelimit errors
Without this commit, running e2e tests could cause this error: `Failed when signing up user
LimitExceededException: Exceeded daily email limit for the operation or the account. If a higher
limit is required, please configure your user pool to use your own Amazon SES configuration for
sending email.`